services:
  # ----------------------------
  # 1. Zookeeper
  # ----------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: newsbot-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # ----------------------------
  # 2. Kafka
  # ----------------------------
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: newsbot-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Internal - Docker network and External - Localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ----------------------------
  # 3. PostgreSQL
  # ----------------------------
  postgres:
    image: postgres:15-alpine
    container_name: newsbot-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_news:/var/lib/postgresql/data

  # ----------------------------
  # 4. MongoDB
  # ----------------------------
  mongodb:
    image: mongo:6.0
    container_name: newsbot-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  # ----------------------------
  # Kafka UI
  # ----------------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: newsbot-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

volumes:
  postgres_data_news:
  mongo_data: